FONE1light/fone-backend-jdsl

- server/src/main/kotlin/com/fone/filmone/domain/competition/entity/Competition.kt
- server/src/main/kotlin/com/fone/filmone/domain/competition/entity/Prize.kt
- server/src/main/kotlin/com/fone/filmone/infrastructure/competition/CompetitionRepositoryImpl.kt
- server/src/main/kotlin/com/fone/filmone/presentation/competition/CompetitionDto.kt
- server/src/main/kotlin/com/fone/filmone/presentation/competition/RegisterCompetitionDto.kt
> [feat-85] 공모전 스펙 수정 반영

- .github/workflows/deploy-api-to-prod.yml
- home/src/main/kotlin/com/fone/home/presentation/HomeController.kt
Reverts FONE1light/fone-backend-jdsl#229
> Revert "[#228] API 서버를 무중단 배포로 변경"

- common/build.gradle.kts
- server/src/main/kotlin/com/fone/filmone/config/SwaggerConfig.kt
> [#249]: common에 불필요한 의존성 제거

- chatting/build.gradle.kts
- chatting/src/main/kotlin/com/fone/chatting/domain/actor/RoomActor.kt
- home/build.gradle.kts
> [#248] kotlin-logging으로 로깅 프레임워크 통일

- server/src/main/kotlin/com/fone/filmone/config/SwaggerConfig.kt
Pageable에 관한 정보가 정상적으로 나타나지 않은 문제와
Principal이 Controller 함수에 포함되는 경우 swagger-ui에 name 파라메터으로 표시되는 문제 해결
> [FO-96] swagger-ui에 오류 해결

- server/src/main/kotlin/com/fone/user/domain/entity/User.kt
- server/src/main/kotlin/com/fone/user/presentation/dto/common/UserDto.kt
> [FO-118] 회원탈퇴 여러번 하는 경우 전화번호가 같음으로 생기는 오류 수정

- home/src/main/kotlin/com/fone/home/presentation/HomeController.kt
- 일단 선 머지해서, 에러 해결하는 것이 먼저 인 것 같아서 완전히 해결됐는지 확인부터 진행할게요. 
- 리팩토링은 나중에 별도로 진행하는게 좋을 것 같습니다.
> [FO-207] home api 로 인한 전체 api 장애 해결

- common/src/main/kotlin/com/fone/common/exception/GlobalExceptionHandler.kt
- server/src/test/kotlin/com/fone/etc/HttpModelFailureResponseTest.kt
api에 값 누락하는 경우 파악하기 쉽지 않은 문제가 있어 추가합니다.
> [FO-211] DTO에 빠진 값 있는 경우 클라이언트에 알리도록 수정

- common/src/main/kotlin/com/fone/common/repository/UserCommonRepository.kt
- server/src/main/kotlin/com/fone/profile/domain/service/RetrieveProfilesService.kt
- server/src/main/kotlin/com/fone/profile/presentation/dto/RetrieveProfilesDto.kt
- server/src/main/kotlin/com/fone/profile/presentation/dto/common/ProfileDto.kt
- server/src/main/kotlin/com/fone/user/infrastructure/UserCommonRepositoryImpl.kt
지금 main 버전에서 서버 실행이 잘 안되는 것 같은데 @DoodlesOnMyFood 님은 잘 되실까요?
> [FO-216] 프로필 조회에 유저 닉네임 추가

- server/src/main/kotlin/com/fone/user/presentation/dto/SignUpUserDto.kt
> [FO-289] 회원가입 비밀번호 !@# 특수문자로 인식 못함

- server/src/main/kotlin/com/fone/user/domain/repository/OauthRepository.kt
- server/src/main/kotlin/com/fone/user/infrastructure/AppleOauthRepository.kt
- server/src/main/kotlin/com/fone/user/infrastructure/GoogleOauthRepository.kt
- server/src/main/kotlin/com/fone/user/infrastructure/KakaoOauthRepository.kt
- server/src/main/kotlin/com/fone/user/infrastructure/NaverOauthRepository.kt
- server/src/test/kotlin/com/fone/user/infrastructure/GoogleOauthRepositoryTest.kt
id token 적용했습니다.
@sinkyoungdeok 님이 주신 토큰의 경우 email 정보가 포함되어 있지 않았습니다. 테스트하실 때 참조 바랍니다.
> [FO-305] Google 소셜 로그인 방식 access token -> id token 인증으로 변경

- server/src/main/kotlin/com/fone/user/presentation/dto/SignUpUserDto.kt
> [FO-484] 회원가입시 비밀번호 대문자 이슈

- server/src/main/kotlin/com/fone/user/domain/entity/User.kt
- server/src/main/kotlin/com/fone/user/presentation/dto/SignUpUserDto.kt
- server/src/test/kotlin/com/fone/common/CommonUserCallApi.kt
- server/src/test/kotlin/com/fone/user/presentation/controller/EmailUserAuthenticationTest.kt
- server/src/test/kotlin/com/fone/user/presentation/controller/SignUpUserControllerTest.kt
기존 API를 바꾸기 때문에 AOS, IOS 모두 적용 가능한지 검토바랍니다.
> [FO-414] 유저 정보에 Name 필드 추가

- common/src/main/kotlin/com/fone/common/exception/ServerException.kt
- server/src/main/kotlin/com/fone/jobOpening/domain/service/RetrieveMySimilarJobOpeningService.kt
- server/src/main/kotlin/com/fone/user/application/ModifyUserFacade.kt
- server/src/main/kotlin/com/fone/user/domain/entity/User.kt
- server/src/main/kotlin/com/fone/user/domain/enum/Job.kt
- server/src/main/kotlin/com/fone/user/domain/service/ModifyUserService.kt
- server/src/main/kotlin/com/fone/user/domain/service/SignUpUserService.kt
- server/src/main/kotlin/com/fone/user/presentation/controller/ModifyUserController.kt
- server/src/main/kotlin/com/fone/user/presentation/dto/ModifyUserDto.kt
- server/src/test/kotlin/com/fone/common/CommonUserCallApi.kt
- server/src/test/kotlin/com/fone/jobOpening/presentation/controller/RetrieveJobOpeningControllerTest.kt
- server/src/test/kotlin/com/fone/user/presentation/controller/ModifyUserControllerTest.kt
- server/src/test/kotlin/com/fone/user/presentation/controller/SignUpUserControllerTest.kt
기존 작업하던게 상당 부분이 FO-525에 겹쳐서 해당 이슈가 완료된 걸로 착각했습니다.
대신 해당 이슈는 사소한 일이 되어버렸네요.
> [FO-491] 유저에 VERIFIED job 추가

- server/src/main/resources/application.yml
로컬환경에서 해당 옵션이 있을 때 오히려 방해된다는 느낌이 들어서, 끄고자합니다.
> [feat] show sql 변경

- server/src/main/kotlin/com/fone/user/domain/entity/User.kt
default 값이 없어서, null로 들어가서 로그인이 안되는현상이 있었습니다.
지금은 db로 직접 false로 바꿔둔 상태여서 문제는 발생하지 않지만, 나중을 위해서미리 추가해둡니다.
> [FO-491] user verified hotfix

- server/src/main/resources/application-prod1.yml
- server/src/main/resources/application-prod2.yml
- server/src/main/resources/application.yml
- properties에 있는 값들 환경변수로 옮깁니다.
- 리뷰 후에 env파일도 업데이트해둘게요.
- env파일 업데이트 해야되기 때문에, 머지 바로 하지 말아주세요.
> [feat] properties env로 변경

- .github/workflows/deploy-api-to-test.yml
테스트 서버에 비용적 이유 때문에 메모리가 다소 적습니다.
그런 메모리 제약으로 JVM 인스턴스를 2개를 동시에 운영하는건 어려움으 블루-그린 배포는 설정하지 않았습니다.
> [FO-728] 테스트 서버 워크플로우 추가

- common/src/main/kotlin/com/fone/common/exception/GlobalExceptionHandler.kt
- ios에서는 이미 header에 보내고 있었고, aos에서는 이번 변경으로 추가했습니다.
> [FO-768] 앱 os type, version code, version name 를 header값 추적

- server/src/main/kotlin/com/fone/jobOpening/domain/entity/JobOpening.kt
- server/src/main/kotlin/com/fone/jobOpening/domain/entity/Work.kt
- server/src/main/kotlin/com/fone/jobOpening/infrastructure/JobOpeningRepositoryImpl.kt
- server/src/main/kotlin/com/fone/jobOpening/presentation/dto/RegisterJobOpeningDto.kt
- server/src/main/kotlin/com/fone/jobOpening/presentation/dto/common/JobOpeningDto.kt
- server/src/main/kotlin/com/fone/jobOpening/presentation/dto/common/WorkDto.kt
- server/src/main/kotlin/com/fone/profile/domain/entity/Profile.kt
- server/src/main/kotlin/com/fone/profile/domain/service/RegisterProfileService.kt
- server/src/main/kotlin/com/fone/profile/presentation/dto/RegisterProfileDto.kt
- server/src/main/kotlin/com/fone/profile/presentation/dto/common/ProfileDto.kt
- server/src/test/kotlin/com/fone/common/CommonJobOpeningCallApi.kt
- server/src/test/kotlin/com/fone/jobOpening/presentation/controller/PutJobOpeningControllerTest.kt
- server/src/test/kotlin/com/fone/jobOpening/presentation/controller/RegisterJobOpeningControllerTest.kt
Reverts FONE1light/fone-backend-jdsl#384
> Revert "[FO-807] 구인구직 모집,프로필 2차 MVP 개선 하면서 필요 없어진 필드 제거 (개발서버만 반영)"

- server/src/main/kotlin/com/fone/jobOpening/domain/entity/JobOpening.kt
- server/src/main/kotlin/com/fone/jobOpening/domain/entity/Work.kt
- server/src/main/kotlin/com/fone/jobOpening/infrastructure/JobOpeningRepositoryImpl.kt
- server/src/main/kotlin/com/fone/jobOpening/presentation/dto/RegisterJobOpeningDto.kt
- server/src/main/kotlin/com/fone/jobOpening/presentation/dto/common/JobOpeningDto.kt
- server/src/main/kotlin/com/fone/jobOpening/presentation/dto/common/WorkDto.kt
- server/src/main/kotlin/com/fone/profile/domain/entity/Profile.kt
- server/src/main/kotlin/com/fone/profile/domain/service/RegisterProfileService.kt
- server/src/main/kotlin/com/fone/profile/presentation/dto/RegisterProfileDto.kt
- server/src/main/kotlin/com/fone/profile/presentation/dto/common/ProfileDto.kt
- server/src/test/kotlin/com/fone/common/CommonJobOpeningCallApi.kt
- server/src/test/kotlin/com/fone/jobOpening/presentation/controller/PutJobOpeningControllerTest.kt
- server/src/test/kotlin/com/fone/jobOpening/presentation/controller/RegisterJobOpeningControllerTest.kt
Reverts FONE1light/fone-backend-jdsl#386
> Revert "Revert "[FO-807] 구인구직 모집,프로필 2차 MVP 개선 하면서 필요 없어진 필드 제거 (개발서버만 반영)""

- server/src/test/kotlin/com/fone/common/CommonCompetitionCallApi.kt
- https://github.com/FONE1light/fone-backend-jdsl/pull/420 해당 버그를 잡기위해서 테스트코드 변경합니다.
> [공모전] 조회 버그 수정 - 테스트코드 변경

- server/src/main/kotlin/com/fone/jobOpening/domain/service/LocationService.kt
지난 회의에 IOS 측에서 요청한 변경 사항.
AOS도 큰 문제 없으면 전체를 상단에 놓는 것이 좀 더 자연스럽다고 생각됩니다.
> [FO-976] '전체'를 시군구 목록 상단에 놓도록 변경

- server/src/main/resources/email-template.html
네이버 메일 같은 서비스들은 css class 지원하지 않아 이메일에 텍스트만 표시되는 문제
> [FO-1010] 일부 이메일 서비스에 css가 나타나지 않는 문제 픽스

- server/src/main/kotlin/com/fone/jobOpening/infrastructure/JobOpeningRepositoryImpl.kt
제가 멍청했습니다.
다음에 복붙을 할때 다시 한번 살펴보도록 하겠습니다.
> [FO-1042] 구인구직에 gender 명시되어 있지 않으면 값이 안 나오는 오류 픽스의 픽스
